RULES = [
    {
        "id": "R1",
        "level": "High",
        "if_text": "glucose >= 126 AND hba1c >= 6.5",
        "then_text": "Risiko High",
        "condition": lambda d: d["glucose"] >= 126 and d["hba1c"] >= 6.5,
    },
    {
        "id": "R2",
        "level": "High",
        "if_text": "glucose >= 126 AND bmi >= 25",
        "then_text": "Risiko High",
        "condition": lambda d: d["glucose"] >= 126 and d["bmi"] >= 25,
    },
    {
        "id": "R3",
        "level": "High",
        "if_text": "hba1c >= 6.5 AND hypertension = 1",
        "then_text": "Risiko High",
        "condition": lambda d: d["hba1c"] >= 6.5 and d["hypertension"] == 1,
    },
    {
        "id": "R4",
        "level": "High",
        "if_text": "glucose >= 126 AND heart_disease = 1",
        "then_text": "Risiko High",
        "condition": lambda d: d["glucose"] >= 126 and d["heart_disease"] == 1,
    },
    {
        "id": "R5",
        "level": "High",
        "if_text": "bmi >= 30 AND hba1c >= 6.5",
        "then_text": "Risiko High",
        "condition": lambda d: d["bmi"] >= 30 and d["hba1c"] >= 6.5,
    },
    {
        "id": "R6",
        "level": "High",
        "if_text": "glucose >= 140 AND age >= 45",
        "then_text": "Risiko High",
        "condition": lambda d: d["glucose"] >= 140 and d["age"] >= 45,
    },
    {
        "id": "R7",
        "level": "High",
        "if_text": "glucose >= 126 AND smoking = Current",
        "then_text": "Risiko High",
        "condition": lambda d: d["glucose"] >= 126 and d["smoking"] == "Current",
    },
    {
        "id": "R8",
        "level": "High",
        "if_text": "hba1c >= 7.0",
        "then_text": "Risiko High",
        "condition": lambda d: d["hba1c"] >= 7.0,
    },
    {
        "id": "R9",
        "level": "High",
        "if_text": "bmi >= 28 AND hypertension = 1",
        "then_text": "Risiko High",
        "condition": lambda d: d["bmi"] >= 28 and d["hypertension"] == 1,
    },
    {
        "id": "R10",
        "level": "High",
        "if_text": "glucose >= 150",
        "then_text": "Risiko High",
        "condition": lambda d: d["glucose"] >= 150,
    },
    {
        "id": "R11",
        "level": "High",
        "if_text": "hba1c >= 6.5 AND age >= 45",
        "then_text": "Risiko High",
        "condition": lambda d: d["hba1c"] >= 6.5 and d["age"] >= 45,
    },
    {
        "id": "R12",
        "level": "High",
        "if_text": "glucose >= 130 AND bmi >= 27",
        "then_text": "Risiko High",
        "condition": lambda d: d["glucose"] >= 130 and d["bmi"] >= 27,
    },
    {
        "id": "R13",
        "level": "High",
        "if_text": "heart_disease = 1 AND hba1c >= 6.5",
        "then_text": "Risiko High",
        "condition": lambda d: d["heart_disease"] == 1 and d["hba1c"] >= 6.5,
    },
    {
        "id": "R14",
        "level": "High",
        "if_text": "smoking = Current AND glucose >= 120",
        "then_text": "Risiko High",
        "condition": lambda d: d["smoking"] == "Current" and d["glucose"] >= 120,
    },
    {
        "id": "R15",
        "level": "High",
        "if_text": "age >= 55 AND bmi >= 25",
        "then_text": "Risiko High",
        "condition": lambda d: d["age"] >= 55 and d["bmi"] >= 25,
    },
    {
        "id": "R16",
        "level": "Medium",
        "if_text": "glucose 100-125",
        "then_text": "Risiko Medium",
        "condition": lambda d: 100 <= d["glucose"] <= 125,
    },
    {
        "id": "R17",
        "level": "Medium",
        "if_text": "hba1c 5.7-6.4",
        "then_text": "Risiko Medium",
        "condition": lambda d: 5.7 <= d["hba1c"] <= 6.4,
    },
    {
        "id": "R18",
        "level": "Medium",
        "if_text": "bmi 23-24.9",
        "then_text": "Risiko Medium",
        "condition": lambda d: 23 <= d["bmi"] <= 24.9,
    },
    {
        "id": "R19",
        "level": "Medium",
        "if_text": "age 35-44 AND glucose >= 110",
        "then_text": "Risiko Medium",
        "condition": lambda d: 35 <= d["age"] <= 44 and d["glucose"] >= 110,
    },
    {
        "id": "R20",
        "level": "Medium",
        "if_text": "smoking = Former AND bmi >= 25",
        "then_text": "Risiko Medium",
        "condition": lambda d: d["smoking"] == "Former" and d["bmi"] >= 25,
    },
    {
        "id": "R21",
        "level": "Medium",
        "if_text": "hypertension = 1 AND glucose >= 110",
        "then_text": "Risiko Medium",
        "condition": lambda d: d["hypertension"] == 1 and d["glucose"] >= 110,
    },
    {
        "id": "R22",
        "level": "Medium",
        "if_text": "heart_disease = 1 AND bmi >= 25",
        "then_text": "Risiko Medium",
        "condition": lambda d: d["heart_disease"] == 1 and d["bmi"] >= 25,
    },
    {
        "id": "R23",
        "level": "Medium",
        "if_text": "age >= 45 AND glucose >= 100",
        "then_text": "Risiko Medium",
        "condition": lambda d: d["age"] >= 45 and d["glucose"] >= 100,
    },
    {
        "id": "R24",
        "level": "Medium",
        "if_text": "bmi >= 25 AND hba1c 5.7-6.4",
        "then_text": "Risiko Medium",
        "condition": lambda d: d["bmi"] >= 25 and 5.7 <= d["hba1c"] <= 6.4,
    },
    {
        "id": "R25",
        "level": "Medium",
        "if_text": "smoking = Current AND bmi >= 25",
        "then_text": "Risiko Medium",
        "condition": lambda d: d["smoking"] == "Current" and d["bmi"] >= 25,
    },
    {
        "id": "R26",
        "level": "Low",
        "if_text": "glucose < 100 AND hba1c < 5.7",
        "then_text": "Risiko Low",
        "condition": lambda d: d["glucose"] < 100 and d["hba1c"] < 5.7,
    },
    {
        "id": "R27",
        "level": "Low",
        "if_text": "bmi < 23 AND glucose < 100",
        "then_text": "Risiko Low",
        "condition": lambda d: d["bmi"] < 23 and d["glucose"] < 100,
    },
    {
        "id": "R28",
        "level": "Low",
        "if_text": "age < 35 AND glucose < 95",
        "then_text": "Risiko Low",
        "condition": lambda d: d["age"] < 35 and d["glucose"] < 95,
    },
    {
        "id": "R29",
        "level": "Low",
        "if_text": "hypertension = 0 AND heart_disease = 0 AND glucose < 100",
        "then_text": "Risiko Low",
        "condition": lambda d: d["hypertension"] == 0 and d["heart_disease"] == 0 and d["glucose"] < 100,
    },
    {
        "id": "R30",
        "level": "Low",
        "if_text": "hba1c < 5.5 AND bmi < 22",
        "then_text": "Risiko Low",
        "condition": lambda d: d["hba1c"] < 5.5 and d["bmi"] < 22,
    },
]
